Feature: Mediated NotebookLM Workflow via Antigravity 2.0
  As an academic researcher studying Buddhism and Esotericism
  I want Knowledge OS to export structured bundles and task prompts for Antigravity 2.0 to process with its NotebookLM skill
  And I want to import the resulting Markdown/text artifacts back into Knowledge OS with source metadata
  So that I can maintain grounded study guides, audio overview summaries, and briefing docs without false direct-sync claims.

  Background:
    Given The Knowledge OS application runs fully client-side and offline-capable
    And A topic "Vi Diệu Pháp Toàn Tập" exists with associated notes and bibliography resources

  Scenario: 1. Export a topic bundle for Antigravity 2.0
    Given A topic has exegesis content, knowledge links, notes, and local/web resources
    When The user exports the Antigravity 2.0 handoff bundle
    Then The bundle identifies "Antigravity 2.0" as the processing agent
    And The bundle identifies "NotebookLM skill" as the downstream processing target
    And The bundle contains the full topic context across structured sections
    And The bundle contains zero credentials, cookies, or session tokens

  Scenario: 2. Generate a NotebookLM task prompt for Antigravity 2.0
    Given The user selects an artifact type "study_guide"
    When The task prompt is generated
    Then The prompt instructs Antigravity 2.0 to invoke its NotebookLM skill
    And The prompt specifies the expected Markdown output structure
    And The prompt does not claim that Knowledge OS has a direct NotebookLM API connection

  Scenario: 3. Export remains completely local and offline
    Given The user has no active internet connection
    When The user exports the bundle or copies the task prompt
    Then The operation succeeds immediately in-memory
    And No remote network requests are dispatched by Knowledge OS

  Scenario: 4. Import a valid artifact with metadata
    Given A processed Markdown artifact generated by Antigravity 2.0 for topic "topic-abhidharma"
    When The user imports the artifact with title "Tóm Tắt Khảo Luận Tâm Sở" and valid content
    Then The artifact is stored with source "antigravity-2.0"
    And The target is recorded as "notebooklm"
    And The status is marked as "imported"
    And The artifact receives a unique identifier

  Scenario: 5. Reject empty artifact content
    Given The user attempts to import an artifact with empty or whitespace-only content
    When The user submits the import form
    Then The import is rejected
    And A specific validation error message "Nội dung artifact không được để trống" is displayed

  Scenario: 6. Reject invalid notebook URL
    Given The user provides a notebook URL "ftp://invalid-url" or "not-a-url"
    When The user submits the artifact import
    Then The import is rejected
    And A specific URL validation error message "URL NotebookLM phải bắt đầu bằng http:// hoặc https://" is displayed

  Scenario: 7. Preserve existing artifacts and avoid accidental overwrite
    Given An artifact already exists for topic "topic-abhidharma"
    When A new artifact is imported for the same topic
    Then The existing artifact remains intact in storage
    And The new artifact is prepended with its own unique identifier

  Scenario: 8. Avoid false direct-integration claims in UI
    Given The NotebookLM Studio modal is opened
    When The user inspects the workflow description and badges
    Then The UI explicitly states that workflow is mediated via Antigravity 2.0
    And The UI does not state that Knowledge OS directly syncs with Google NotebookLM
